#undef TAPPING_TERM
#define TAPPING_TERM 150

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define NO_ACTION_ONESHOT

// Shift / paren setup
#undef LSPO_KEYS
#undef RSPC_KEYS
#define LSPO_KEYS KC_LEFT_SHIFT, KC_RIGHT_ALT, KC_QUOT
#define RSPC_KEYS KC_RIGHT_SHIFT, KC_RIGHT_ALT, KC_NUHS
